name: Setup System and Rust
description: Setup System and Rust
inputs:
  token:
    description: Github token
    required: false
    default: ''
  target:
    description: toolchain target triple
    required: false
  setup-arg:
    description: Argument for the system setup script
    required: false
    default: ''
  save-cache:
    description: Whether to save the System cache
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Restore cached LLVM and Clang
      if: ${{ runner.os == 'Windows' }}
      id: cache-llvm-restore
      uses: actions/cache/restore@v4
      with:
        key: llvm-15
        path: C:/Program Files/LLVM

    - name: Install LLVM and Clang
      if: ${{ runner.os == 'Windows' }}
      uses: KyleMayes/install-llvm-action@v2
      with:
        cached: ${{ steps.cache-llvm-restore.outputs.cache-hit }}
        version: '15'

    - name: Save LLVM and Clang
      if: ${{ runner.os == 'Windows' && inputs.save-cache == 'true' }}
      id: cache-llvm-save
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache-llvm-restore.outputs.cache-primary-key }}
        path: C:/Program Files/LLVM

    - name: Remove all Clang compilers on Windows
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        # Remove ALL clang executables system-wide so CMake can only find MSVC.
        # libclang.dll is preserved for bindgen.

        # 1. Nuke all .exe in our installed LLVM (keeps libclang.dll which is a .dll)
        $llvmBin = "C:\Program Files\LLVM\bin"
        if (Test-Path $llvmBin) {
          Get-ChildItem "$llvmBin\*.exe" | Remove-Item -Force
          Write-Host "Removed all executables from $llvmBin"
        }

        # 2. Remove LLVM CMake config so CMake can't discover LLVM as a toolchain
        $llvmCmake = "C:\Program Files\LLVM\lib\cmake"
        if (Test-Path $llvmCmake) {
          Remove-Item $llvmCmake -Recurse -Force
          Write-Host "Removed LLVM CMake configs"
        }

        # 3. Check for VS-bundled Clang (optional component of Build Tools)
        $vsClangPaths = @(
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm",
          "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm",
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm",
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm"
        )
        foreach ($p in $vsClangPaths) {
          if (Test-Path $p) {
            Remove-Item $p -Recurse -Force
            Write-Host "Removed VS-bundled Clang at $p"
          }
        }

        # 4. Set LIBCLANG_PATH for bindgen (points to our LLVM where libclang.dll lives)
        echo "LIBCLANG_PATH=$llvmBin" >> $env:GITHUB_ENV

        # 5. Find cl.exe full path via vswhere and set CMAKE_C_COMPILER
        $vsPath = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" `
          -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
          -property installationPath
        $msvcVer = (Get-Content "$vsPath\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt").Trim()
        $clExe = "$vsPath\VC\Tools\MSVC\$msvcVer\bin\HostX64\x64\cl.exe"
        if (Test-Path $clExe) {
          echo "CMAKE_C_COMPILER=$clExe" >> $env:GITHUB_ENV
          echo "CMAKE_CXX_COMPILER=$clExe" >> $env:GITHUB_ENV
          Write-Host "Set CMAKE_C_COMPILER to $clExe"
        } else {
          Write-Error "Could not find cl.exe at $clExe"
          exit 1
        }

        # 6. Verify no clang is discoverable anywhere in PATH
        foreach ($name in @('clang', 'clang++', 'clang-cl')) {
          $found = Get-Command $name -ErrorAction SilentlyContinue
          if ($found) {
            Write-Error "$name still found at: $($found.Source)"
            exit 1
          }
        }
        Write-Host "All Clang compilers removed. MSVC cl.exe set as CMAKE compiler."

    - name: Install current Bash on macOS
      shell: bash
      if: runner.os == 'macOS'
      run: brew install bash

    - name: Install Nasm
      if: ${{ runner.os != 'Linux' }}
      uses: ilammy/setup-nasm@v1

    - name: Install Mold (linker)
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        curl -L# 'https://github.com/rui314/mold/releases/download/v2.4.0/mold-2.4.0-x86_64-linux.tar.gz' \
        | sudo tar -xzf- -C /usr/local

    - name: Remove 32-bit libs and incompatible pre-installed pkgs from Runner
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        set -eux
        if dpkg -l | grep i386; then
          sudo apt-get purge --allow-remove-essential libc6-i386 ".*:i386" || true
          sudo dpkg --remove-architecture i386 || true
        fi

        # https://github.com/actions/runner-images/issues/9546#issuecomment-2014940361
        sudo apt-get remove libunwind-* || true

    - name: Setup Rust and Dependencies
      uses: ./.github/actions/setup-rust
      with:
        target: ${{ inputs.target }}
        save-cache: ${{ inputs.save-cache }}

    - name: Run setup.sh script
      shell: bash
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: ./scripts/setup.sh ${{ inputs.setup-arg }}

    - name: Run setup.ps1 script
      shell: powershell
      if: ${{ runner.os == 'Windows' }}
      run: ./scripts/setup.ps1

    - name: Setup native dependencies
      shell: bash
      env:
        TARGET_TRIPLE: ${{ inputs.target }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: cargo run -p xtask -- setup
